### ISSUE TITLE
Version 0.7.1 does not follow semantic versioning rules with 0.7.0

### ISSUE THREAD

**Issue by ryan-summers** [smoltcp-rs/smoltcp#472]
It appears that the 0.7.1 release does not follow semantic versioning rules with 0.7.0 - specifically, if the smoltcp dependency is specified as:
```
[dependencies.smoltcp]
version = "0.7.0"
features = ["ethernet", "proto-ipv4"]
```

Cargo may instead choose to use smoltcp =0.7.1. If the above feature flags are provided to smoltcp 0.7.1, the build will fail.

Given that the feature flags changed between 0.7.0 and 0.7.1, it seems that 0.7.1 is not following the semantic versioning rules. 

I would recommend that we yank 0.7.1 and re-release it as 0.8.0

cc: @Dirbaio

**Comment by Dirbaio** [comment]
The `compile_error!` checks were added for build combinations that were already broken before (as far as I know, at least). #416 #447 . They add human-readable info on why the build is broken with these features, but shouldn't cause any build that worked before to stop working.

And indeed, that featureset doesn't build in v0.7.0 nor v0.7.1. v0.7.1 adds the friendly error message

```
[dirbaio@mars smoltcp]$ git checkout v0.7.0
[dirbaio@mars smoltcp]$ cargo build --no-default-features --features ethernet,proto-ipv4
error[E0392]: parameter `'b` is never used
   --> src/socket/set.rs:182:21
    |
182 | pub struct Iter<'a, 'b: 'a> {
    |                     ^^ unused parameter
    |
..etcetc, lots of errors
[dirbaio@mars smoltcp]$ git checkout v0.7.1
[dirbaio@mars smoltcp]$ cargo build --no-default-features --features ethernet,proto-ipv4
error: If you enable the socket feature, you must enable at least one of the following features: socket-raw, socket-udp, socket-tcp, socket-icmp
  --> src/lib.rs:98:1
   |
98 | compile_error!("If you enable the socket feature, you must enable at least one of the following features: socket-raw, socket-udp, socket-tcp, socket-icmp");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0392]: parameter `'b` is never used
   --> src/socket/set.rs:182:21
    |
182 | pub struct Iter<'a, 'b: 'a> {
    |                     ^^ unused parameter
    |
...etc lots of errors
```

Maybe there's something extra going on. Can you check which features are actually enabled in your project with `cargo tree --format '{p} {f}'`? with both v0.7.0 and v0.7.1.

**Comment by ryan-summers** [comment]
The key here is that the `stm32h7xx-hal` uses smoltcp as a dependency, but only implements `phy::Device` for the ethernet module so that external users can continue to use the PHY as they would like.

Whether this is a valid means of using smoltcp is up for debate, but it _did_ compile, and since the stm32h7xx-hal crate doesn't actually do any protocol parsing (it just implements the trait), this was a valid configuration.

Applications then also specified a `smoltcp` dependency that then had to have all the necessary feature flags.

Maybe a good solution here is to move the phy::Device trait to some external crate so that HALs can implement it without pulling in smoltcp?

Edit: Collecting data, please wait

**Comment by ryan-summers** [comment]
Hmm.. Okay, after investigating further, it appears that there's a bug in the `stm32h7xx-hal` Cargo.toml that causes the feature-flags in dev-dependencies to propagate into the original `smoltcp` dependency, which enabled `sockets-raw`. Let me see if I can resolve things outside of smoltcp and I'll see if this all resolves.

**Comment by ryan-summers** [comment]
Closing this as resolved - it looks like dev-dependency unification bugs in Cargo caused this issue in `stm32h7xx-hal`. Thanks for the feedback!

**Comment by Sympatron** [comment]
@ryan-summers Maybe using [the new feature resolver](https://doc.rust-lang.org/beta/cargo/reference/resolver.html#resolver-versions) will solve this? As far as I understand this, this is exactly the kind of thing that should be solved now.

**Comment by ryan-summers** [comment]
Yeah, but it's still in beta, unfortunately, so we can't use that in the `stm32h7xx-hal`

**Comment by Sympatron** [comment]
It got stabilized recently: https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-151-2021-03-25

**Comment by ryan-summers** [comment]
Ooh, I was wondering. I'll look into it - thanks for the intel

**Comment by Dirbaio** [comment]
Seeing all the pain the Cargo features are causing, I'm starting to think it makes more sense to ensure smoltcp builds with all possible feature combinations, even those that "don't make sense", and only have features for stuff that bloats the binary even if unused
